name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: compile
      run: mvn clean install
    
    - name: package
      run: mvn package
    
    - name: unit test
      run: mvn test
    
    - name: working directory
      run: pwd
      
    - name: list the current directory
      run: ls -a
    
    - name: what is in target folder
      run: |
        cd target
        ls -a
    - name: analize with sonarcloud
      run: mvn verify sonar:sonar -Dsonar.projectKey=mvn- -Dsonar.organization=gh -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=de0f9420847bbbdd9dbd49b1b13e278300abb33e
      
    - name: scp to remote
      uses: horochx/deploy-via-scp@1.1.0
      with:
        local: /home/runner/work/testrepo/testrepo/target/my-app-1.0-SNAPSHOT.jar
        remote: /home/ubuntu
        host: 52.202.54.83
        port: 22
        user: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: deployment
      uses: appleboy/ssh-action@main
      with:
        host: 52.202.54.83
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
         cd /home/ubuntu
         nohup java -jar my-app-SNAPSHOT.jar &      
